# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm publish

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm pack --filename=package.tgz
      - uses: Klemensas/action-autotag@stable
        id: update_tag
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUBTOKEN }}"
          tag_prefix: "v"
      - name: Create Release
        if: steps.update_tag.outputs.tagname
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUBTOKEN }}"
        with:
          tag_name: ${{ steps.update_tag.outputs.tagname }}
          release_name: Release ${{ steps.update_tag.outputs.tagname }}
      - name: Upload Release Asset
        if: steps.update_tag.outputs.tagname
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUBTOKEN }}"
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package.tgz
          asset_name: package.tgz
          asset_content_type: application/tgz

